use DUAN1_QLBANDIENTHOAI
go

IF OBJECT_ID('GiamGiaSP') IS NOT NULL
DROP TABLE GiamGiaSP
GO 
CREATE TABLE GiamGiaSP(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaGiamGiaSP int identity(1,1),
    SoTienCL MONEY DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    ID_SanPham UNIQUEIDENTIFIER,
    ID_GiamGia UNIQUEIDENTIFIER,
)
IF OBJECT_ID('GiamGia') IS NOT NULL 
DROP TABLE GiamGia
GO
CREATE TABLE GiamGia(
     Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
      MaGiamGia NVARCHAR(10) UNIQUE,
      TenGiamGia NVARCHAR(100) DEFAULT NULL,
      LoaiGiamGia NVARCHAR(100) DEFAULT NULL,
	  NgayBatDau Date DEFAULT NULL,
	  NgayKetThuc Date DEFAULT NULL,
      MucGiamGia NVARCHAR(50) DEFAULT NULL,
      TrangThai INT DEFAULT NULL
)

IF OBJECT_ID('IMEI_KT') IS NOT NULL
DROP TABLE IMEI_KT
GO
CREATE TABLE IMEI_KT
(
   Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
   MaImei NVARCHAR(10) DEFAULT NULL,
   TrangThai INT DEFAULT NULL,
   ID_HDCT UNIQUEIDENTIFIER
)

--CREATE TABLE HDCT
IF OBJECT_ID('HDCT') IS NOT NULL
DROP TABLE HDCT
GO
CREATE TABLE HDCT
(
   Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
   SoLuong INT DEFAULT NULL,
   DonGia MONEY DEFAULT NULL,
   TienThua MONEY DEFAULT NULL,
   TienGiamGia MONEY DEFAULT NULL,
   TrangThai INT DEFAULT NULL,
   Id_SanPham UNIQUEIDENTIFIER,
   Id_HoaDon UNIQUEIDENTIFIER,
)

-- CREATE TABLE IMEI
IF OBJECT_ID('IMEI') IS NOT NULL
DROP TABLE IMEI 
GO
CREATE TABLE IMEI
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaImei NVARCHAR(50) DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    Id_Sp UNIQUEIDENTIFIER
)
IF OBJECT_ID('SANPHAM') IS NOT NULL
DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaSP NVARCHAR(10) DEFAULT NULL,
    TenSP NVARCHAR(200) DEFAULT NULL,
    GiaNhap MONEY DEFAULT NULL,
    GiaBan MONEY DEFAULT NULL,
    SoLuongTon INT DEFAULT NULL,
    MoTa NVARCHAR(300) DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    NamBH INT DEFAULT NULL,
    Id_DLuong UNIQUEIDENTIFIER,
    Id_MauSac UNIQUEIDENTIFIER,
    Id_XuatXu UNIQUEIDENTIFIER,
    Id_PhanLoai UNIQUEIDENTIFIER,
    Id_Pin UNIQUEIDENTIFIER,
    Id_Chip UNIQUEIDENTIFIER,
    Id_Ram UNIQUEIDENTIFIER,
    Id_ManHinh UNIQUEIDENTIFIER,
    Id_KichThuoc UNIQUEIDENTIFIER,
	MaCTSP NVARCHAR(20) DEFAULT NULL
)

--CREATE TABLE DungLuong 
IF OBJECT_ID('DungLuong') IS NOT NULL
DROP TABLE DungLuong 
GO
CREATE TABLE DungLuong
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaDL NVARCHAR(10) UNIQUE,
    TenDL NVARCHAR(10) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)
--CREATE TABLE MAUSAC
IF OBJECT_ID('MauSac') IS NOT NULL
DROP TABLE MauSac 
GO
CREATE TABLE MauSac
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaMau NVARCHAR(10) UNIQUE,
    TenMau NVARCHAR(10) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE XUATXU
IF OBJECT_ID('XuatXu') IS NOT NULL
DROP TABLE XuatXu 
GO
CREATE TABLE XuatXu
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Ma NVARCHAR(10) UNIQUE,
    TenNoiXX NVARCHAR(100) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE PhanLoaiHang
IF OBJECT_ID('PhanLoaiHang') IS NOT NULL
DROP TABLE PhanLoaiHang 
GO
CREATE TABLE PhanLoaiHang
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaLH NVARCHAR(10) UNIQUE,
    TenLH NVARCHAR(50) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE PIN
IF OBJECT_ID('Pin') IS NOT NULL
DROP TABLE Pin 
GO
CREATE TABLE Pin
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaPin NVARCHAR(10) UNIQUE,
    TenPin NVARCHAR(80) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE Chip 
IF OBJECT_ID('CHIP') IS NOT NULL
DROP TABLE CHIP 
GO
CREATE TABLE CHIP
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaChip NVARCHAR(10) UNIQUE,
    TenChip NVARCHAR(20) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE RAM 
IF OBJECT_ID('RAM') IS NOT NULL
DROP TABLE RAM 
GO
CREATE TABLE RAM
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaRam NVARCHAR(10) UNIQUE,
    TenRAM NVARCHAR(30) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE ManHinh
IF OBJECT_ID('ManHinh') IS NOT NULL
DROP TABLE ManHinh 
GO
CREATE TABLE ManHinh
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaMH NVARCHAR(10) UNIQUE,
    TenMH NVARCHAR(50) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

--CREATE TABLE KICHTHUOC
IF OBJECT_ID('KichThuoc') IS NOT NULL
DROP TABLE KichThuoc 
GO
CREATE TABLE KichThuoc
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaKT NVARCHAR(10) UNIQUE,
    TenKT NVARCHAR(100) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

IF OBJECT_ID('HTTT') IS NOT NULL 
DROP TABLE HTTT 
GO 
CREATE TABLE HTTT(
     Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
     MaHTT NVARCHAR(10) DEFAULT NULL,
     TenHT NVARCHAR(100) DEFAULT NULL,
     NgayTao Date DEFAULT NULL,
     NgaySua Date DEFAULT NULL,
     TongTien MONEY DEFAULT NULL,
     TrangThai INT DEFAULT NULL,
     Id_HoaDon  UNIQUEIDENTIFIER
)
--create table LichSuTieuDiem
IF OBJECT_ID('LichSuDiem')  IS NOT NULL
DROP TABLE LichSuDiem 
GO
CREATE TABLE LichSuDiem(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SoDiemDung float DEFAULT NULL,
    NgaySD DATE DEFAULT NULL,
    SoDiemCong float DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    Id_QuyDoi UNIQUEIDENTIFIER,
    Id_Diem int identity(1,1),
    Id_HoaDon UNIQUEIDENTIFIER
)
--CREATE TABLE QuyDoi 
IF OBJECT_ID('QuyDoi') IS NOT NULL
DROP TABLE QuyDoi 
GO 
CREATE TABLE QuyDoi(
       Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
       TienTichDiem MONEY DEFAULT NULL,
       TienTieuDiem Money DEFAULT NULL,
       TrangThai INT DEFAULT NULL
)
--CREATE TABLE HoaDon
IF OBJECT_ID('HoaDon') IS NOT NULL
DROP TABLE HoaDon
GO
CREATE TABLE HoaDon
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaHD int identity(1,1),
    MaNV NVARCHAR(10) DEFAULT NULL,
    NgayTao DATE DEFAULT NULL,
    SoLuong INT DEFAULT NULL,
    NgayThanhToan DATETIME DEFAULT NULL,
    NgayShip DATE DEFAULT NULL,
    NgayNhan DATE DEFAULT NULL,
    TenKH NVARCHAR(100) DEFAULT NULL ,
    DiaChi NVARCHAR(200) DEFAULT NULL,
    TongTien MONEY DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    SDTNguoiNhan NVARCHAR(10) DEFAULT NULL,
    SDTNguoiShip NVARCHAR(10) DEFAULT NULL,
    TenNguoiShip NVARCHAR(100) DEFAULT NULL,
    PhanTramGiamGia DECIMAL(5,2) DEFAULT NULL,
    SoDemSD INT DEFAULT NULL,
    SoTienQuyDoi MONEY DEFAULT NULL,
    Id_KhachHang UNIQUEIDENTIFIER,
    Id_NhanVien UNIQUEIDENTIFIER
)
--CREATE TABLE KhachHang
IF OBJECT_ID('KhachHang') IS NOT NULL
DROP TABLE KhachHang
GO
CREATE TABLE KhachHang
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaKH NVARCHAR(10)DEFAULT NULL,
    HoTen NVARCHAR(100) DEFAULT NULL,
    SDT NVARCHAR(10) DEFAULT NULL,
    NgaySinh DATE DEFAULT NULL,
    DiaChi NVARCHAR(100) DEFAULT NULL,
    GioiTinh INT DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    GhiChu NVARCHAR(200) DEFAULT NULL,
    SoLanMua INT DEFAULT NULL,
	Id_Diem int identity(1,1)
)

IF OBJECT_ID('Diem') IS NOT NULL
DROP TABLE Diem
GO
CREATE TABLE Diem
(
    Id int identity(1,1) PRIMARY KEY,
	SoDiem float DEFAULT NULL,
	TrangThai int DEFAULT NULL
)

--CREATE TABLE GiaoCa
IF OBJECT_ID('GiaoCa') IS NOT NULL 
DROP TABLE GiaoCa 
GO 
CREATE TABLE GiaoCa(
   Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
   MaGiaoCa INT IDENTITY(1,1),
   ThoiGianNhanCa DATETIME  DEFAULT NULL,
   ThoiGianGiaoCa DATETIME DEFAULT NULL,
   Id_NhanVienTrongCa   UNIQUEIDENTIFIER,
   Id_NhanVienCaTiepTheo  UNIQUEIDENTIFIER,
   TienBanDau MONEY DEFAULT NULL,
   TongTienTrongCa MONEY DEFAULT NULL,
   TongTienMat MONEY DEFAULT NULL,
   TongTienKhac MONEY DEFAULT NULL,
   TienPhatSinh MONEY DEFAULT NULL,
   GhiChuPhatSinh NVARCHAR(200) DEFAULT NULL,
   TongTienMatCaTruoc MONEY DEFAULT NULL,
   ThoiGianReset TIME DEFAULT NULL,
   TongTienMatDaRut MONEY DEFAULT NULL,
   TrangThai INT DEFAULT NULL
)

--CREATE TABLE NHANVIEN
IF OBJECT_ID('NhanVien') is not NULL
DROP TABLE NhanVien
GO
CREATE TABLE NhanVien
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaNV NVARCHAR(10) DEFAULT NULL,
    Ten NVARCHAR(10) DEFAULT NULL,
    TenDem NVARCHAR(20) DEFAULT NULL,
    Ho NVARCHAR(10) DEFAULT NULL,
    GioiTinh INT DEFAULT NULL,
    NgaySinh DATE DEFAULT NULL,
    DiaChi NVARCHAR(200) DEFAULT NULL,
    SDT NVARCHAR(10) DEFAULT NULL,
    Email NVARCHAR(100) DEFAULT NULL,
    MatKhau NVARCHAR(30) DEFAULT NULL,
    TrangThai INT DEFAULT NULL,
    NgayBDLV DATE DEFAULT NULL,
    GhiChu NVARCHAR(150) DEFAULT NULL,
    Id_ChucVu UNIQUEIDENTIFIER
)
--CREATE TABLE ChucVu
IF OBJECT_ID('ChucVu') is not NULL
DROP TABLE ChucVu
GO
CREATE TABLE ChucVu
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MaCV NVARCHAR(10) DEFAULT NULL,
    TenCV NVARCHAR(100) DEFAULT NULL,
    TrangThai INT DEFAULT NULL
)

ALTER TABLE GiaoCa ADD FOREIGN KEY (Id_NhanVienTrongCa) REFERENCES NhanVien(Id)

ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_DLuong) REFERENCES DungLuong(Id)
--SANPHAM - MauSac
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_MauSac) REFERENCES MauSac(Id)
--SANPHAM - XuatXu
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_XuatXu) REFERENCES XuatXu(Id)
--SANPHAM - PhanLoaiHang
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_PhanLoai) REFERENCES PhanLoaiHang(Id)
--SANPHAM - PIN
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_Pin) REFERENCES PIN(Id)
--SANPHAM - Chip
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_Chip) REFERENCES Chip(Id)
--SANPHAM - RAM
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_Ram) REFERENCES RAM(Id)
--SANPHAM - ManHinh
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_ManHinh) REFERENCES ManHinh(Id)
--SANPHAM - KichThuoc
ALTER TABLE SANPHAM ADD FOREIGN KEY (Id_KichThuoc) REFERENCES KichThuoc(Id)
--SANPHAM-ChucVu
ALTER TABLE NhanVien ADD FOREIGN KEY (Id_ChucVu) REFERENCES ChucVu(Id)
--KhachHang - HoaDon 
ALTER TABLE HoaDon ADD FOREIGN KEY ( Id_KhachHang) REFERENCES KhachHang(Id)
--NhanVien - HoaDon 
ALTER TABLE HoaDon ADD FOREIGN KEY (Id_NhanVien) REFERENCES NhanVien(Id)
--HDCT - HoaDon 
ALTER TABLE HDCT ADD FOREIGN KEY (Id_HoaDon) REFERENCES HoaDon(Id)
--HDCT - SanPham 
ALTER TABLE HDCT ADD FOREIGN KEY (Id_SanPham) REFERENCES SANPHAM(Id)
--IMEI - SanPham
ALTER TABLE IMEI ADD FOREIGN KEY (Id_Sp) REFERENCES SANPHAM(Id)

ALTER TABLE GiamGiaSP ADD FOREIGN KEY (ID_SanPham) REFERENCES SANPHAM(Id)
--IMEI - SanPham
ALTER TABLE GiamGiaSP ADD FOREIGN KEY (ID_GiamGia) REFERENCES GiamGia(Id)

ALTER TABLE KhachHang ADD FOREIGN KEY (Id_Diem) REFERENCES Diem(Id)

ALTER TABLE  LichSuDiem ADD FOREIGN KEY (Id_Diem) REFERENCES Diem(Id)

ALTER TABLE  LichSuDiem ADD FOREIGN KEY (Id_QuyDoi) REFERENCES QuyDoi(Id)

ALTER TABLE  LichSuDiem ADD FOREIGN KEY (Id_HoaDon) REFERENCES HoaDon(Id)

ALTER TABLE HTTT ADD FOREIGN KEY (Id_HoaDon) REFERENCES HoaDon(Id)

ALTER TABLE HDCT ADD FOREIGN KEY (Id_HoaDon) REFERENCES HoaDon(Id)

ALTER TABLE Imei_KT ADD FOREIGN KEY (ID_HDCT) REFERENCES HDCT(Id)
